#!/bin/bash

# Hia! I am script ran from gentoo chroot

source /etc/profile
env-update

# we play very dirty games with runlevels
rm -rf /var/lib/init.d

# uncomment this line if you need normally running system:
#/sbin/rc default

# Run per-chroot local script, if it exists
if [ -x /run_from_chroot.local ]; then
       /run_from_chroot.local "$@"
else
# or just to poke some stuff interactively use this one:
       /bin/bash "$@"
fi
